
-- Create or update messages table if needed
create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  content text not null check (char_length(content) <= 500),
  inserted_at timestamptz default now()
);

-- Enable realtime
alter publication supabase_realtime add table public.messages;

