name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build application
      run: npm run build
    
    - name: Build Docker image
      run: docker build -t chat-app:${{ github.sha }} .
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: dist/

  # Uncomment and configure this job when you're ready to deploy
  # deploy:
  #   needs: build-and-test
  #   if: github.ref == 'refs/heads/main'
  #   runs-on: ubuntu-latest
  #   
  #   steps:
  #   - uses: actions/checkout@v3
  #   
  #   - name: Download build artifacts
  #     uses: actions/download-artifact@v3
  #     with:
  #       name: build-artifacts
  #       path: dist/
  #   
  #   - name: Set up Docker Buildx
  #     uses: docker/setup-buildx-action@v2
  #   
  #   - name: Login to Docker Hub
  #     uses: docker/login-action@v2
  #     with:
  #       username: ${{ secrets.DOCKERHUB_USERNAME }}
  #       password: ${{ secrets.DOCKERHUB_TOKEN }}
  #   
  #   - name: Build and push Docker image
  #     uses: docker/build-push-action@v4
  #     with:
  #       context: .
  #       push: true
  #       tags: ${{ secrets.DOCKERHUB_USERNAME }}/chat-app:latest,${{ secrets.DOCKERHUB_USERNAME }}/chat-app:${{ github.sha }}
  #   
  #   # Choose one of the deployment options below based on your preference
  #   
  #   # Option 1: Deploy to Render
  #   # - name: Deploy to Render
  #   #   env:
  #   #     RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
  #   #     SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
  #   #   run: |
  #   #     curl -X POST "https://api.render.com/v1/services/$SERVICE_ID/deploys" \
  #   #       -H "Authorization: Bearer $RENDER_API_KEY" \
  #   #       -H "Content-Type: application/json"
  #   
  #   # Option 2: Deploy to Heroku
  #   # - name: Login to Heroku Container Registry
  #   #   env:
  #   #     HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  #   #   run: heroku container:login
  #   # 
  #   # - name: Build and push to Heroku
  #   #   env:
  #   #     HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  #   #     HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
  #   #   run: |
  #   #     heroku container:push web --app $HEROKU_APP_NAME
  #   #     heroku container:release web --app $HEROKU_APP_NAME 