name: Docker CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build and test Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          load: true
          tags: chat-app:test
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      # If you have tests, uncomment and adjust the following step
      # - name: Run tests
      #   run: |
      #     docker run --rm chat-app:test npm test
  
  # Uncomment the following job if you want to push to Docker Hub
  # publish:
  #   needs: build
  #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
  #   runs-on: ubuntu-latest
  #   
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3
  #       
  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v2
  #     
  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v2
  #       with:
  #         username: ${{ secrets.DOCKER_HUB_USERNAME }}
  #         password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
  #     
  #     - name: Build and push
  #       uses: docker/build-push-action@v4
  #       with:
  #         context: .
  #         push: true
  #         tags: ${{ secrets.DOCKER_HUB_USERNAME }}/chat-app:latest
  #         cache-from: type=gha
  #         cache-to: type=gha,mode=max
  
  # Uncomment the following job if you want to deploy to a hosting service
  # deploy:
  #   needs: publish
  #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
  #   runs-on: ubuntu-latest
  #   
  #   steps:
  #     - name: Deploy to hosting service
  #       run: echo "Add deployment steps here"
  #       # Example for Heroku
  #       # - uses: akhileshns/heroku-deploy@v3
  #       #   with:
  #       #     heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
  #       #     heroku_app_name: "your-app-name"
  #       #     heroku_email: "your-email@example.com"
  #       #     usedocker: true 